# -*- mode: ruby -*-
# vi: set ft=ruby :
SERVER_COUNT = 3

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2

  end
  (1..SERVER_COUNT).each do |i|
    config.vm.define "consul#{i}-server" do |node|
      node.vm.box = "hashicorp/bionic64"
      node.vm.hostname = "consul-server#{i}"
      node.vm.provision "shell", run: "always" do |s|
        s.path = "provision.sh"
        s.args = ["/vagrant/consul/consul#{i}-config.json", "/vagrant/consul.conf", "/vagrant/consul.service"]
      end
      node.vm.network "private_network", ip: "172.20.20.1#{i}"
      #node.vm.network "forwarded_port", guest: 8500, host: 8500 + i
    end
  end
  config.vm.define "consulclient" do |client|
    client.vm.box = "hashicorp/bionic64"
    client.vm.hostname = "clientconsul"
    client.vm.provision "shell", run: "always" do |s|
        s.path = "provision.sh"
        s.args = ["/vagrant/consul/consulclient.json", "/vagrant/consul.conf", "/vagrant/consul.service"]
    end
    client.vm.network "private_network", ip: "172.20.20.14"
  end
end