# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_COUNT = 3

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2

  end
  (1..SERVER_COUNT).each do |i|
    config.vm.define "consul-server#{i}" do |node|
      node.vm.box = "hashicorp/bionic64"
      node.vm.hostname = "consul-server#{i}"
      node.vm.provision "shell", run: "always" do |s|
        s.path = "provision.sh"
        s.args = ["/consul/consul#{i}-config.json", "consul.conf"]
      end
      node.vm.network "private_network", ip: "172.20.20.1#{i}"
      #node.vm.network "forwarded_port", guest: 8500, host: 8500 + i
    end
  end
  config.vm.define "consulclient" do |client|
    client.vm.box = "hashicorp/bionic64"
    client.vm.hostname = "clientconsul"
    client.vm.provision "shell", run: "always" do |s|
        s.path = "provision.sh"
        s.args = ["/consul/consulclient.json", "consul.conf"]
    end
    client.vm.network "private_network", ip: "172.20.20.14"
  end
end


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #config.vm.box = "hashicorp/bionic64"
  #config.vm.synced_folder ".", "/vagrant", :create => true
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2

  end

  config.vm.define "consul1" do |consul1|
    config.vm.provision "shell", run: "always" do |s|
        s.path = "provision.sh"
        s.args = ["/vagrant/consul/consul1-config.json", "/vagrant/consul.conf"]
    end
    consul1.vm.hostname = "consul1"
    consul1.vm.network "private_network", ip: "172.20.20.10"
    consul1.vm.network "forwarded_port", guest: 8500, host: 8501
  end

  config.vm.define "consul2" do |consul2|
    config.vm.provision "shell", run: "always" do |s|
        s.path = "provision.sh"
        s.args = ["/vagrant/consul/consul2-config.json", "/vagrant/consul.conf"]
    end
    consul2.vm.hostname = "consul2"
    consul2.vm.network "private_network", ip: "172.20.20.20"
    consul2.vm.network "forwarded_port", guest: 8500, host: 8502
  end

  config.vm.define "consul3" do |consul3|
    config.vm.provision "shell", run: "always" do |s|
        s.path = "provision.sh"
        s.args = ["/vagrant/consul/consul3-config.json", "/vagrant/consul.conf"]
    end
    consul3.vm.hostname = "consul3"
    consul3.vm.network "private_network", ip: "172.20.20.30"
    consul3.vm.network "forwarded_port", guest: 8500, host: 8503
  end

  config.vm.define "consulclient" do |client|
    config.vm.provision "shell", run: "always" do |s|
        s.path = "provisionclient.sh"
        s.args = ["/vagrant/consul/consulclient-config.json", "/vagrant/consul.conf"]
    end
    client.vm.hostname = "consulclient"
    client.vm.network "private_network", ip: "172.20.20.40"
  end
end
