version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul-enterprise:1.8.3-ent
    container_name: consul-server
    hostname: consul-server
    restart: always
    volumes:
     - .server1.json:/consul/config/server.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - hashicorp
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

networks:
  hashicorp:
    driver: bridge